name: lift_image_vcot
_target_: diffusion_policy.workspace.train_diffusion_unet_image_workspace.TrainDiffusionUnetImageWorkspace

dataset:
  _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
  dataset_path: data/lift/ph/image.hdf5
  shape_meta: &shape_meta
    obs:
      agentview_image:
        shape: [3, 128, 128]
        type: rgb
      robot0_eye_in_hand_image:
        shape: [3, 128, 128]
        type: rgb
    action:
      shape: [7]
  horizon: 16
  pad_before: 1
  pad_after: 7
  seed: 42
  val_ratio: 0.02
  n_obs_steps: 2

shape_meta: *shape_meta

env_runner:
  _target_: diffusion_policy.env_runner.robomimic_image_runner.RobomimicImageRunner # Runner 이름 수정됨
  dataset_path: data/lift/ph/image.hdf5
  shape_meta: *shape_meta
  n_train: 6
  n_train_vis: 2
  train_start_idx: 0
  n_test: 50
  n_test_vis: 4
  test_start_seed: 100000
  max_steps: 400
  crf: 22
  fps: 10
  # past_action: False
  # new_simulation: True
  # latency_steps: 0
  # use_cache: True
  # seed: 42
